Duration:
    20: 
        pose: [3.35, -2.35, 0.0]
        mode: ['singel-pose', 1]
        level: [2, 'r']
    90: 
        pose: [-2.5, 4.0, 3.0]
        mode: ['singel-pose', 1]
        level: [2, 'r']