Events:
    '1': 
        pose: [0.0, 0.0, 0.0]
        mode: ['singel-pose', 1]
        level: [2, 'r']

    '2': 
        pose: [0.0, 1.34, 0.0]
        mode: ['singel-pose', 1]
        level: [2, 'r']

    '3': 
        pose: [[1.3, 3.64, 0.0],[3.45, 3.74, -1.0]]
        mode: ['singel-pose', 1]
        level: [2, 'r']

    '4': 
        pose: [0.0, 2.34, 0.0]
        mode: ['singel-pose', 1]
        level: [2, 'r']

    '5': 
        pose: [[3.35, 3.5, -1.57],[2.35, 0.2, -1.57]]                                                                                                                                                                                                                                                                                                                                                     
        mode: ['singel-pose', 1]
        level: [2, 'r']

    '6': 
        pose: [0.0, 3.34, 3.0]                                                                                                                                                                                                                                                                                                                                                       
        mode: ['singel-pose', 1]
        level: [2, 'r']