# Duration:
#     10: 
#         pose: [[3.5, 2.85, 0.0], [2.93, 0.0, -1.57],[0.0, 0.0, 3.0]]
#         mode: ['circle_cruise', 5]
#         level: [2, 'r']

Events:
    '1': 
        pose: [0.0, 0.0, 0.0]
        mode: ['singel-pose', 1]
        level: [2, 'r']

    '2': 
        pose: [1.43, 1.95, 0.0]
        mode: ['singel-pose', 1]
        level: [2, 'r']

    '3': 
        pose: [2.58, 2.85, 0.0]
        mode: ['singel-pose', 1]
        level: [2, 'r']

    '4': 
        pose: [2.93, 0.0, -1.57]
        mode: ['singel-pose', 1]
        level: [2, 'r']

    '5': 
        pose: [1.0, 0.0, 0.0]                                                                                                                                                                                                                                                                                                                                                     
        mode: ['singel-pose', 1]
        level: [2, 'r']

    '6': 
        pose: [0.0, 1.0, 0.0]                                                                                                                                                                                                                                                                                                                                                   
        mode: ['singel-pose', 1]
        level: [2, 'r']