Events:
    '1': 
        pose: [9.65, -6.4, 3.14]
        mode: ['singel-pose', 1]
        level: [2, 'r']

    '2': 
        pose: [[9.25,-3.7, 3.14],[6.45,-3.25,3.14]]
        mode: ['singel-pose', 1]
        level: [2, 'r']

    '3': 
        pose: [[9.25,-3.7, 3.14],[6.45,-3.25,3.14]]
        mode: ['singel-pose', 1]
        level: [2, 'r']

    #  '3': 
    #     pose: [[8.15,-1.6,3.14],[4.7, -3.5, 3.14]]
    #     mode: ['singel-pose', 1]
    #     level: [2, 'r']



# Events:
#     '1': 
#         pose: [-0.86, -2.14, 0.0]
#         mode: ['singel-pose', 1]
#         level: [2, 'r']

#     '2': 
#         pose: [-4.53, -8.39, -1.57]
#         mode: ['singel-pose', 1]
#         level: [2, 'r']

#     '3': 
#         pose: [[4.32, 4.11, 0.0],[6.0, 4.35, 0.0]]
#         mode: ['singel-pose', 1]
#         level: [2, 'r']

#     '4': 
#         pose: [5.17, -6.19, 0.0]
#         mode: ['singel-pose', 1]
#         level: [2, 'r']

#     '5': 
#         pose: [[7.2, 4.21, -1.57],[3.37, -0.14, -2.0]]
#         mode: ['singel-pose', 1]
#         level: [2, 'r']

#     '6': 
#         pose: [[2.42, 4.56, 3.1],[-0.93, 4.56, 3.1],[-0.83, 3.01, -1.57]]
#         mode: ['singel-pose', 1]
#         level: [2, 'r']