Duration:
    15: 
        # pose: [[3.0, 0.0, -1.7],[0.0, 0.0, -3.0]]
        # pose: [[1.3, 3.64, 0.0],[3.45, 3.74, -1.0],[2.35, 0.2, -1.7],[3.45, 3.74, 1.0],[1.3, 3.64, 3.0],[0.3, 0.0, -1.57]]
        pose: [[2.0, 3.5, 0.0],[3.35, 3.5, 0.0]]
        # pose: [[2.0, -3.1, -1.57],[0.0, 0.0, -3.0]]
        mode: ['singel-pose', 1]
        level: [2, 'r']

    45: 
        # pose: [[3.0, 0.0, -1.7],[0.0, 0.0, -3.0]]
        # pose: [[1.3, 3.64, 0.0],[3.45, 3.74, -1.0],[2.35, 0.2, -1.7],[3.45, 3.74, 1.0],[1.3, 3.64, 3.0],[0.3, 0.0, -1.57]]
        pose: [[0.0, 3.5, 3.0],[0.0, 0.0, -1.57]]
        # pose: [[2.0, -3.1, -1.57],[0.0, 0.0, -3.0]]
        mode: ['singel-pose', 1]
        level: [2, 'r']

