# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'map_edit_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 700)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 150, 141, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.view_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.view_pushButton.setObjectName("view_pushButton")
        self.verticalLayout.addWidget(self.view_pushButton)
        self.obstacle_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.obstacle_pushButton.setObjectName("obstacle_pushButton")
        self.verticalLayout.addWidget(self.obstacle_pushButton)
        self.free_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.free_pushButton.setObjectName("free_pushButton")
        self.verticalLayout.addWidget(self.free_pushButton)
        self.unexplored_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.unexplored_pushButton.setObjectName("unexplored_pushButton")
        self.verticalLayout.addWidget(self.unexplored_pushButton)
        self.save_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.save_pushButton.setObjectName("save_pushButton")
        self.verticalLayout.addWidget(self.save_pushButton)
        self.exit_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.exit_pushButton.setObjectName("exit_pushButton")
        self.verticalLayout.addWidget(self.exit_pushButton)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(210, 60, 550, 550))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.view_pushButton.setText(_translate("Dialog", "view mode"))
        self.obstacle_pushButton.setText(_translate("Dialog", "obstacle zone"))
        self.free_pushButton.setText(_translate("Dialog", "free zone"))
        self.unexplored_pushButton.setText(_translate("Dialog", "unexplored zone"))
        self.save_pushButton.setText(_translate("Dialog", "save"))
        self.exit_pushButton.setText(_translate("Dialog", "exit"))
        self.label.setText(_translate("Dialog", "TextLabel"))
