# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.map_label = QtWidgets.QLabel(self.centralwidget)
        self.map_label.setGeometry(QtCore.QRect(390, 60, 630, 630))
        self.map_label.setObjectName("map_label")
        self.config_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.config_groupBox.setGeometry(QtCore.QRect(1060, 50, 360, 720))
        self.config_groupBox.setObjectName("config_groupBox")
        self.config_show_treeWidget = QtWidgets.QTreeWidget(self.config_groupBox)
        self.config_show_treeWidget.setGeometry(QtCore.QRect(20, 30, 320, 400))
        self.config_show_treeWidget.setObjectName("config_show_treeWidget")
        self.config_show_treeWidget.headerItem().setText(0, "1")
        self.delete_one_item_pushButton = QtWidgets.QPushButton(self.config_groupBox)
        self.delete_one_item_pushButton.setGeometry(QtCore.QRect(20, 450, 320, 25))
        self.delete_one_item_pushButton.setObjectName("delete_one_item_pushButton")
        self.treeWidget = QtWidgets.QTreeWidget(self.config_groupBox)
        self.treeWidget.setGeometry(QtCore.QRect(20, 490, 320, 210))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.status_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.status_groupBox.setGeometry(QtCore.QRect(30, 50, 320, 720))
        self.status_groupBox.setObjectName("status_groupBox")
        self.map_edit_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.map_edit_pushButton.setGeometry(QtCore.QRect(390, 720, 90, 30))
        self.map_edit_pushButton.setObjectName("map_edit_pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen_map = QtWidgets.QAction(MainWindow)
        self.actionOpen_map.setObjectName("actionOpen_map")
        self.actionSave_config = QtWidgets.QAction(MainWindow)
        self.actionSave_config.setObjectName("actionSave_config")
        self.menuFile.addAction(self.actionOpen_map)
        self.menuFile.addAction(self.actionSave_config)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.map_label.setText(_translate("MainWindow", "TextLabel"))
        self.config_groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.delete_one_item_pushButton.setText(_translate("MainWindow", "Delete One Item"))
        self.status_groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.map_edit_pushButton.setText(_translate("MainWindow", "edit map"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_map.setText(_translate("MainWindow", "Open map"))
        self.actionSave_config.setText(_translate("MainWindow", "Save config"))
